name: Update YTS RSS Feed

on:
  schedule:
    # Run every hour at minute 0
    - cron: '0 * * * *'
  workflow_dispatch: # Allow manual trigger
  push:
    branches: [ main ]

jobs:
  update-rss:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Add permission to write to repository
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Node.js dependencies
      run: npm ci
      
    - name: Install Python dependencies
      run: pip install -r requirements.txt
      
    - name: Generate RSS feeds
      run: node index.js
      
    - name: Auto-add RSS feeds to Real-Debrid config
      run: python3 rd_rss.py --auto-add-feeds
      
    - name: Process RSS feeds to Real-Debrid
      env:
        RD_TOKEN: ${{ secrets.RD_TOKEN }}
      run: |
        if [ -n "$RD_TOKEN" ]; then
          echo "Processing RSS feeds to Real-Debrid..."
          python3 rd_rss.py
        else
          echo "RD_TOKEN not set, skipping Real-Debrid processing"
        fi
      
    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add feeds/ RDRSSconfig/ || true
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update RSS feeds and RD config - $(date)"
          git push
        fi